apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.name" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: {{ include "app.name" . }}
    {{ if .Values.app.juiceshop.ingress.external_dns.enabled }}
    external-dns.alpha.kubernetes.io/ingress-hostname-source: annotation-only
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.app.juiceshop.ingress.url }}
    external-dns.alpha.kubernetes.io/ttl: "60"
    {{ end }}
spec:
  tls:
  - hosts:
    - {{ .Values.app.juiceshop.ingress.url }}
    secretName: example-tls
  #adding port temporarily to disable traffic
  rules:
  - host: {{ .Values.app.juiceshop.ingress.url }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "app.name" . }}
            port:
              number: 80
